//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonApi.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonApi.Test.ExampleResponses", typeof(ExampleResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;base_happiness&quot;: 50,
        ///  &quot;capture_rate&quot;: 45,
        ///  &quot;color&quot;: {
        ///    &quot;name&quot;: &quot;red&quot;,
        ///    &quot;url&quot;: &quot;https://pokeapi.co/api/v2/pokemon-color/8/&quot;
        ///  },
        ///  &quot;egg_groups&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;monster&quot;,
        ///      &quot;url&quot;: &quot;https://pokeapi.co/api/v2/egg-group/1/&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;dragon&quot;,
        ///      &quot;url&quot;: &quot;https://pokeapi.co/api/v2/egg-group/14/&quot;
        ///    }
        ///  ],
        ///  &quot;evolution_chain&quot;: {
        ///    &quot;url&quot;: &quot;https://pokeapi.co/api/v2/evolution-chain/2/&quot;
        ///  },
        ///  &quot;evolves_from_species&quot;: {
        ///    &quot;name&quot;: &quot;charmeleon&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Charizard {
            get {
                return ResourceManager.GetString("Charizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;success&quot;: {
        ///        &quot;total&quot;: 1
        ///    },
        ///    &quot;contents&quot;: {
        ///        &quot;translated&quot;: &quot;Spits fire yond is hot enow to melt boulders. Known to cause forest fires unintentionally.&quot;,
        ///        &quot;text&quot;: &quot;Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.&quot;,
        ///        &quot;translation&quot;: &quot;shakespeare&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string CharizardShakespeare {
            get {
                return ResourceManager.GetString("CharizardShakespeare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;base_happiness&quot;: 0,
        ///  &quot;capture_rate&quot;: 3,
        ///  &quot;color&quot;: {
        ///    &quot;name&quot;: &quot;purple&quot;,
        ///    &quot;url&quot;: &quot;https://pokeapi.co/api/v2/pokemon-color/7/&quot;
        ///  },
        ///  &quot;egg_groups&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;no-eggs&quot;,
        ///      &quot;url&quot;: &quot;https://pokeapi.co/api/v2/egg-group/15/&quot;
        ///    }
        ///  ],
        ///  &quot;evolution_chain&quot;: {
        ///    &quot;url&quot;: &quot;https://pokeapi.co/api/v2/evolution-chain/77/&quot;
        ///  },
        ///  &quot;evolves_from_species&quot;: null,
        ///  &quot;flavor_text_entries&quot;: [
        ///    {
        ///      &quot;flavor_text&quot;: &quot;It was created by\na scientist after\nyears of horrific\fgene  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mewtwo {
            get {
                return ResourceManager.GetString("Mewtwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;success&quot;: {
        ///        &quot;total&quot;: 1
        ///    },
        ///    &quot;contents&quot;: {
        ///        &quot;translated&quot;: &quot;Created by a scientist after years of horrific gene splicing and dna engineering experiments,  it was.&quot;,
        ///        &quot;text&quot;: &quot;It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.&quot;,
        ///        &quot;translation&quot;: &quot;yoda&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string MewtwoYoda {
            get {
                return ResourceManager.GetString("MewtwoYoda", resourceCulture);
            }
        }
    }
}
